name: "debug_evals"
# ckpt_dir: !!CHANGETHIS!!
# dataset_dir: !!CHANGETHIS!!
# dump_dir: !!CHANGETHIS!!
tasks: boolq,hellaswag,nq,piqa,siqa,tqa,winogrande,obqa,arc_easy,arc_challenge,race.middle,race.high,gsm8k,bbh,mmlu,copa,human_eval_plus,mbpp
generator:
  compile_prefilling: false
  reduce_generation_overhead: false
  max_tokens: 8192
  dtype: bf16

mp_size: 1
